POST http://localhost:5000/validateMove
Content-Type: application/json

{
  "from": "A1",
  "to": "C3",
  "piece": "bishop",
  "color": "white",
  "board": [{"position": "B2", "piece": "pawn", "color": "black"}, {"position": "C2", "piece": "pawn", "color": "black"}]
}
