### Initialize the board
POST http://localhost:5000/initializeBoard
Content-Type: application/json

###
### Get the current board state
# @name getBoard
GET http://localhost:5000/board

###
### Validate a move using the fetched board
POST http://localhost:5000/validateMove
Content-Type: application/json

{
  "from": "A7",
  "to": "A8",
  "piece": "pawn",
  "color": "white",
  "hasMoved": true,
  "fullPiece": {
      "position": "A7",
      "piece": "pawn",
      "color": "white",
      "hasMoved": true,
      "moveNum": 2
  }
}