POST http://localhost:5000/validateMove
Content-Type: application/json

{
  "from": "C2",
  "to": "B1",
  "piece": "pawn",
  "color": "black",
  "board": [{"position": "B6", "piece": "pawn", "color": "black"}, {"position": "B1", "piece": "pawn", "color": "white"}]
}
